spring:
  messages:
    encoding: UTF-8

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: never
  sql:
    init:
      mode: always
    show-sql: true

  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: true

  application:
    name: Books app. Thymeleaf version


  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always

#h2:
#  console:
#    path: /h2-consol
#    settings:
#      web-allow-others: true

logging:
  level:
    ROOT: ERROR
