spring:
  messages:
    encoding: UTF-8

  application:
    name: staff

  data:
    rest:
      basePath: /api

  datasource:
    url: jdbc:postgresql://localhost:5432/staff
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

