spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"
  application:
    name: quiz-app
  shell:
    command:
      script:
        enabled: false
      version:
        enabled: false

application:
  version: 1.4
  locale: ru_RU
  io:
    input: system
  resource:
    location: quiz_@{locale}.csv
